### ISSUE TITLE
Can't access Arclight server

### ISSUE THREAD

**Issue by R1NZLER15** [ArclightPowered/lightfall#1]
Installed both `Lightfall` & `Lightfall client mod` and also `Arclight` for the forge server( `bungeecord` is set to true).
I can access any vanilla/paper server without problem but when trying to access the Arclight server i'm getting this error from the proxy server:

```
[04:35:57] [Netty Worker IO Thread #10/INFO]: [PlayerNameHere|/***.***.***.***] <-> ServerConnector [priv_1] has connected
[04:35:57] [Netty Worker IO Thread #10/INFO]: [/***.***.***.***|PlayerNameHere] <-> DownstreamBridge <-> [survival] has disconnected
[04:35:57] [Netty Worker IO Thread #10/ERROR]: [/***.***.***.***|PlayerNameHere] -> HS Upstream - encountered exception
io.netty.handler.codec.EncoderException: java.lang.IllegalArgumentException: Cannot get ID for packet class net.md_5.bungee.protocol.packet.PlayerListItem in phase LOGIN with direction TO_CLIENT
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125) ~[lightfall.jar:git:lightfall-Bootstrap:1.16-R0.5-SNAPSHOT:c5abaa3:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[lightfall.jar:git:lightfall-Bootstrap:1.16-R0.5-SNAPSHOT:c5abaa3:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764) ~[lightfall.jar:git:lightfall-Bootstrap:1.16-R0.5-SNAPSHOT:c5abaa3:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790) ~[lightfall.jar:git:lightfall-Bootstrap:1.16-R0.5-SNAPSHOT:c5abaa3:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758) ~[lightfall.jar:git:lightfall-Bootstrap:1.16-R0.5-SNAPSHOT:c5abaa3:unknown]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020) ~[lightfall.jar:git:lightfall-Bootstrap:1.16-R0.5-SNAPSHOT:c5abaa3:unknown]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:299) ~[lightfall.jar:git:lightfall-Bootstrap:1.16-R0.5-SNAPSHOT:c5abaa3:unknown]
	at net.md_5.bungee.netty.ChannelWrapper.write(ChannelWrapper.java:60) ~[lightfall.jar:git:lightfall-Bootstrap:1.16-R0.5-SNAPSHOT:c5abaa3:unknown]
	at net.md_5.bungee.UserConnection$1.sendPacket(UserConnection.java:154) ~[lightfall.jar:git:lightfall-Bootstrap:1.16-R0.5-SNAPSHOT:c5abaa3:unknown]
	at codecrafter47.bungeetablistplus.handler.TabOverlayHandlerImpl.sendPacket(TabOverlayHandlerImpl.java:43) ~[?:?]
	at codecrafter47.bungeetablistplus.handler.AbstractTabOverlayHandler$CustomContentTabOverlayHandler.sendQueuedItems(AbstractTabOverlayHandler.java:2044) ~[?:?]
	at codecrafter47.bungeetablistplus.handler.AbstractTabOverlayHandler$CustomContentTabOverlayHandler.update(AbstractTabOverlayHandler.java:2016) ~[?:?]
	at codecrafter47.bungeetablistplus.handler.AbstractTabOverlayHandler.update(AbstractTabOverlayHandler.java:517) ~[?:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[lightfall.jar:git:lightfall-Bootstrap:1.16-R0.5-SNAPSHOT:c5abaa3:unknown]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) ~[lightfall.jar:git:lightfall-Bootstrap:1.16-R0.5-SNAPSHOT:c5abaa3:unknown]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384) ~[lightfall.jar:git:lightfall-Bootstrap:1.16-R0.5-SNAPSHOT:c5abaa3:unknown]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[lightfall.jar:git:lightfall-Bootstrap:1.16-R0.5-SNAPSHOT:c5abaa3:unknown]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[lightfall.jar:git:lightfall-Bootstrap:1.16-R0.5-SNAPSHOT:c5abaa3:unknown]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.IllegalArgumentException: Cannot get ID for packet class net.md_5.bungee.protocol.packet.PlayerListItem in phase LOGIN with direction TO_CLIENT
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:399) ~[lightfall.jar:git:lightfall-Bootstrap:1.16-R0.5-SNAPSHOT:c5abaa3:unknown]
	at net.md_5.bungee.protocol.Protocol$DirectionData.getId(Protocol.java:613) ~[lightfall.jar:git:lightfall-Bootstrap:1.16-R0.5-SNAPSHOT:c5abaa3:unknown]
	at net.md_5.bungee.protocol.MinecraftEncoder.encode(MinecraftEncoder.java:25) ~[lightfall.jar:git:lightfall-Bootstrap:1.16-R0.5-SNAPSHOT:c5abaa3:unknown]
	at net.md_5.bungee.protocol.MinecraftEncoder.encode(MinecraftEncoder.java:10) ~[lightfall.jar:git:lightfall-Bootstrap:1.16-R0.5-SNAPSHOT:c5abaa3:unknown]
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[lightfall.jar:git:lightfall-Bootstrap:1.16-R0.5-SNAPSHOT:c5abaa3:unknown]
	... 18 more
[04:35:57] [Netty Worker IO Thread #10/INFO]: [PlayerNameHere] disconnected with: EncoderException : java.lang.IllegalArgumentException: Cannot get ID for packet class net.md_5.bungee.protocol.packet.PlayerListItem in phase LOGIN with direction TO_CLIENT @ io.netty.handler.codec.MessageToByteEncoder:125
[04:35:57] [Netty Worker IO Thread #10/INFO]: [/***.***.***.***|PlayerNameHere] -> HS Upstream has disconnected
[04:35:57] [Netty Worker IO Thread #10/INFO]: [PlayerNameHere|/***.***.***.***] <-> Modern FML PENDING [priv_1] has disconnected
```
![image](https://user-images.githubusercontent.com/27157220/111065540-945c8c80-8477-11eb-8b96-4ab9ba404a6b.png)

**Comment by IzzelAliz** [comment]
Please have a test with latest build

**Comment by R1NZLER15** [comment]
It lets me join for a split-second but sends me back to the fallback server with no error on neither the proxy nor the arclight server

**Comment by IzzelAliz** [comment]
logs maybe?

**Comment by R1NZLER15** [comment]
That's the issue, there's only "user connected/disconnected" logs, nothing else.
Lightfall:
```
[00:34:14] [Netty Worker IO Thread #5/INFO]: [PlayerName|/***.***.***.***] <-> ServerConnector [login] has connected
[00:34:15] [Netty Worker IO Thread #5/INFO]: [PlayerName|/***.***.***.***] <-> ServerConnector [lobby] has connected
[00:34:16] [Netty Worker IO Thread #5/INFO]: [/***.***.***.***|PlayerName] <-> DownstreamBridge <-> [login] has disconnected
[00:34:26] [Netty Worker IO Thread #5/INFO]: [PlayerName|/***.***.***.***] <-> ServerConnector [priv_1] has connected
[00:34:26] [Netty Worker IO Thread #5/INFO]: [/***.***.***.***|PlayerName] <-> DownstreamBridge <-> [lobby] has disconnected
[00:34:29] [Netty Worker IO Thread #5/INFO] [RedirectPlus]: Redirected PlayerName from priv_1 to lobby
[00:34:29] [Netty Worker IO Thread #5/INFO]: [/***.***.***.***|PlayerName] <-> DownstreamBridge <-> [priv_1] has disconnected
[00:34:29] [Netty Worker IO Thread #5/INFO]: [PlayerName|/***.***.***.***] <-> ServerConnector [lobby] has connected
```

Arclight:
```
[15Mar2021 00:34:26.825] [User Authenticator #1/INFO] [net.minecraft.network.login.ServerLoginNetHandler/]: UUID of player PlayerName is ********************************
[15Mar2021 00:34:29.191] [Server thread/INFO] [net.minecraftforge.common.AdvancementLoadFix/]: Using new advancement loading for net.minecraft.advancements.PlayerAdvancements@45a266a4
[15Mar2021 00:34:29.215] [Server thread/INFO] [net.minecraft.server.management.PlayerList/]: PlayerName[/***.***.***.***] logged in with entity id 407 at (-566.6252207904749, 70.0, -577.5225554932433)
[15Mar2021 00:34:29.379] [Server thread/INFO] [net.minecraft.network.play.ServerPlayNetHandler/]: PlayerName lost connection: Disconnected
[15Mar2021 00:34:29.505] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer/]: PlayerName left the game
```

Client:
![image](https://user-images.githubusercontent.com/27157220/111112722-e22bd000-851d-11eb-9622-342cb96c7f71.png)

**Comment by Arzio** [comment]
> Client:
> ![image](https://user-images.githubusercontent.com/27157220/111112722-e22bd000-851d-11eb-9622-342cb96c7f71.png)

The same is happening with me.

**Comment by denireilly** [comment]
Can confrim this issue aswell for me, but i can seem to connect without being op
