### ISSUE TITLE
java.lang.IllegalArgumentException: Payload too large

### ISSUE THREAD

**Issue by D0ctorLeon** [ArclightPowered/lightfall#27]
Unknown Error. Is there a way to increase Payload size ?

That is the log:
`[/217.85.79.188:60439]: <-> InitialHandler has pinged
09:19:45
[/217.85.79.188:60441]: <-> InitialHandler has connected
09:19:46
[BigDataPackage|/217.85.79.188:60441]: <-> ServerConnector [0Skill_Modpack_1.18.2] has connected
WARN09:19:52
[/217.85.79.188:60441|BigDataPackage]: <-> DownstreamBridge <-> [0Skill_Modpack_1.18.2] - could not decode packet! java.lang.IllegalArgumentException: Payload too large
ERROR09:19:52
io.netty.handler.codec.DecoderException: java.lang.IllegalArgumentException: Payload too large
at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:98)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:311)
at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:432)
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IllegalArgumentException: Payload too large
at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145)
at net.md_5.bungee.protocol.packet.PluginMessage.read(PluginMessage.java:78)
at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:60)
at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:12)
at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)
... 26 more
INFO09:19:52
[BigDataPackage]: disconnected with: The server you were previously on went down, you have been connected to a fallback server
[/217.85.79.188:60441|BigDataPackage]: <-> DownstreamBridge <-> [0Skill_Modpack_1.18.2] has disconnected
[/217.85.79.188:60441|BigDataPackage]: -> UpstreamBridge has disconnected`

**Comment by kingniu4** [comment]
have same problem,wish fix it
