### ISSUE TITLE
加载Fastlogin插件报错

### ISSUE THREAD

**Issue by wcz0** [ArclightPowered/lightfall#36]
`[17:54:11 INFO] [fastlogin.hikari.HikariDataSource]: FastLogin - Start completed.
[17:54:11 WARN]: Exception encountered when loading plugin: FastLogin
java.lang.NoClassDefFoundError: net/md_5/bungee/protocol/Property
	at com.github.games647.fastlogin.bungee.listener.ConnectListener.<init>(ConnectListener.java:99) ~[?:?]
	at com.github.games647.fastlogin.bungee.FastLoginBungee.onEnable(FastLoginBungee.java:104) ~[?:?]
	at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:315) ~[lightfall.jar:git:lightfall-Bootstrap:1.18-R0.1-SNAPSHOT:4409192:26]
	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:290) ~[lightfall.jar:git:lightfall-Bootstrap:1.18-R0.1-SNAPSHOT:4409192:26]
	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67) ~[lightfall.jar:git:lightfall-Bootstrap:1.18-R0.1-SNAPSHOT:4409192:26]
	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[lightfall.jar:git:lightfall-Bootstrap:1.18-R0.1-SNAPSHOT:4409192:26]
Caused by: java.lang.ClassNotFoundException: net.md_5.bungee.protocol.Property
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:103) ~[lightfall.jar:git:lightfall-Bootstrap:1.18-R0.1-SNAPSHOT:4409192:26]
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:59) ~[lightfall.jar:git:lightfall-Bootstrap:1.18-R0.1-SNAPSHOT:4409192:26]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	... 6 more
`

插件无法启用

**Comment by huangdihd** [comment]
我现在使用的最新版本可以正常加载

**Comment by wcz0** [comment]
> 

ok, 感谢你的测试
