### ISSUE TITLE
1.19.2Packet overflow

### ISSUE THREAD

**Issue by Arctc1Fox** [ArclightPowered/lightfall#39]
Jumping to 1.19Forge through lightfall reported errors and dropped calls
**server log↓**
[17:27:57 INFO]: [ArcticFox_ling|/14.150.99.54:31573] <-> ServerConnector [server1] has connected
[17:28:06 WARN]: [/14.150.99.54:31573|ArcticFox_ling] <-> DownstreamBridge <-> [server1] - could not decode packet! java.lang.IndexOutOfBoundsException: Index: 66, Size: 49
[17:28:06 ERROR]: io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: Index: 66, Size: 49
[17:28:06 ERROR]:       at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:98)
[17:28:06 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[17:28:06 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[17:28:06 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[17:28:06 ERROR]:       at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:336)
[17:28:06 ERROR]:       at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:308)
[17:28:06 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[17:28:06 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[17:28:06 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[17:28:06 ERROR]:       at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[17:28:06 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[17:28:06 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[17:28:06 ERROR]:       at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[17:28:06 ERROR]:       at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
[17:28:06 ERROR]:       at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
[17:28:06 ERROR]:       at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
[17:28:06 ERROR]:       at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
[17:28:06 ERROR]:       at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
[17:28:06 ERROR]:       at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[17:28:06 ERROR]:       at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[17:28:06 ERROR]:       at java.lang.Thread.run(Thread.java:853)
[17:28:06 ERROR]: Caused by: java.lang.IndexOutOfBoundsException: Index: 66, Size: 49
[17:28:06 ERROR]:       at java.util.ArrayList.rangeCheck(ArrayList.java:659)
[17:28:06 ERROR]:       at java.util.ArrayList.get(ArrayList.java:435)
[17:28:06 ERROR]:       at net.md_5.bungee.protocol.packet.Commands$ArgumentRegistry.read(Commands.java:661)
[17:28:06 ERROR]:       at net.md_5.bungee.protocol.packet.Commands$ArgumentRegistry.access$000(Commands.java:309)
[17:28:06 ERROR]:       at net.md_5.bungee.protocol.packet.Commands.read(Commands.java:86)
[17:28:06 ERROR]:       at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:60)
[17:28:06 ERROR]:       at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:12)
[17:28:06 ERROR]:       at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)
[17:28:06 ERROR]:       ... 20 more
[17:28:06 INFO]: [ArcticFox_ling] disconnected with: The server you were previously on went down, you have been connected to a fallback server
-------------------------------------------------------------------------------
**Client Error↓**
Internal Exception: java.net.SocketException:Connection reset

**Comment by manugame** [comment]
same issue

**Comment by manugame** [comment]
fixed by enabling ip-forwarding
