### ISSUE TITLE
index out of bound exception when connecting to arclight server

### ISSUE THREAD

**Issue by zaze06** [ArclightPowered/lightfall#41]
Hi, I'm having issues connecting to an arclight server from the lobby server.

From what I see In the logs, I'm the only one getting this except problem, but others can't connect ether.

lightfall version:

error from lightfall
```
[12:58:20 WARN]: [/83.219.211.198:51323|AlienFromDia] <-> DownstreamBridge <-> [modded] - could not decode packet! java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 48
[12:58:20 ERROR]: io.netty.handler.codec.DecoderException: java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 48
[12:58:20 ERROR]:       at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:98)
[12:58:20 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[12:58:20 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[12:58:20 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[12:58:20 ERROR]:       at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[12:58:20 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[12:58:20 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[12:58:20 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[12:58:20 ERROR]:       at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
[12:58:20 ERROR]:       at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:333)
[12:58:20 ERROR]:       at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:454)
[12:58:20 ERROR]:       at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
[12:58:20 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[12:58:20 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[12:58:20 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[12:58:20 ERROR]:       at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[12:58:20 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
[12:58:20 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[12:58:20 ERROR]:       at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[12:58:20 ERROR]:       at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
[12:58:20 ERROR]:       at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
[12:58:20 ERROR]:       at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
[12:58:20 ERROR]:       at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
[12:58:20 ERROR]:       at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
[12:58:20 ERROR]:       at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[12:58:20 ERROR]:       at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[12:58:20 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:1589)
[12:58:20 ERROR]: Caused by: java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 48
[12:58:20 ERROR]:       at net.md_5.bungee.protocol.packet.Commands$ArgumentRegistry.read(Commands.java:781)
[12:58:20 ERROR]:       at net.md_5.bungee.protocol.packet.Commands$ArgumentRegistry.access$000(Commands.java:307)
[12:58:20 ERROR]:       at net.md_5.bungee.protocol.packet.Commands.read(Commands.java:84)
[12:58:20 ERROR]:       at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:60)
[12:58:20 ERROR]:       at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:12)
[12:58:20 ERROR]:       at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)
[12:58:20 ERROR]:       ... 26 more
```

if more info about the other server connected to the proxy or the mods/plugins loaded on the proxy server and arclight server is needed I can provide it. thanks for the help

**Comment by Ghost-chu** [comment]
same 

```
[20:50:25 WARN]: [/[0:0:0:0:0:0:0:1%0]:33354|Ghost_chu] <-> DownstreamBridge <-> [journey] - could not decode packet!
io.netty.handler.codec.DecoderException: java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 48
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:98) ~[lightfall.jar:git:lightfall-Bootstrap:1.20-R0.2-SNAPSHOT:63f9b1b:36]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[lightfall.jar:git:lightfall-Bootstrap:1.20-R0.2-SNAPSHOT:63f9b1b:36]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[lightfall.jar:git:lightfall-Bootstrap:1.20-R0.2-SNAPSHOT:63f9b1b:36]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[lightfall.jar:git:lightfall-Bootstrap:1.20-R0.2-SNAPSHOT:63f9b1b:36]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[lightfall.jar:git:lightfall-Bootstrap:1.20-R0.2-SNAPSHOT:63f9b1b:36]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[lightfall.jar:git:lightfall-Bootstrap:1.20-R0.2-SNAPSHOT:63f9b1b:36]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[lightfall.jar:git:lightfall-Bootstrap:1.20-R0.2-SNAPSHOT:63f9b1b:36]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[lightfall.jar:git:lightfall-Bootstrap:1.20-R0.2-SNAPSHOT:63f9b1b:36]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[lightfall.jar:git:lightfall-Bootstrap:1.20-R0.2-SNAPSHOT:63f9b1b:36]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:333) ~[lightfall.jar:git:lightfall-Bootstrap:1.20-R0.2-SNAPSHOT:63f9b1b:36]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:454) ~[lightfall.jar:git:lightfall-Bootstrap:1.20-R0.2-SNAPSHOT:63f9b1b:36]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290) ~[lightfall.jar:git:lightfall-Bootstrap:1.20-R0.2-SNAPSHOT:63f9b1b:36]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[lightfall.jar:git:lightfall-Bootstrap:1.20-R0.2-SNAPSHOT:63f9b1b:36]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[lightfall.jar:git:lightfall-Bootstrap:1.20-R0.2-SNAPSHOT:63f9b1b:36]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[lightfall.jar:git:lightfall-Bootstrap:1.20-R0.2-SNAPSHOT:63f9b1b:36]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[lightfall.jar:git:lightfall-Bootstrap:1.20-R0.2-SNAPSHOT:63f9b1b:36]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[lightfall.jar:git:lightfall-Bootstrap:1.20-R0.2-SNAPSHOT:63f9b1b:36]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[lightfall.jar:git:lightfall-Bootstrap:1.20-R0.2-SNAPSHOT:63f9b1b:36]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[lightfall.jar:git:lightfall-Bootstrap:1.20-R0.2-SNAPSHOT:63f9b1b:36]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[lightfall.jar:git:lightfall-Bootstrap:1.20-R0.2-SNAPSHOT:63f9b1b:36]
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe$1.run(AbstractEpollChannel.java:425) ~[lightfall.jar:git:lightfall-Bootstrap:1.20-R0.2-SNAPSHOT:63f9b1b:36]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173) ~[lightfall.jar:git:lightfall-Bootstrap:1.20-R0.2-SNAPSHOT:63f9b1b:36]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166) ~[lightfall.jar:git:lightfall-Bootstrap:1.20-R0.2-SNAPSHOT:63f9b1b:36]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[lightfall.jar:git:lightfall-Bootstrap:1.20-R0.2-SNAPSHOT:63f9b1b:36]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:413) ~[lightfall.jar:git:lightfall-Bootstrap:1.20-R0.2-SNAPSHOT:63f9b1b:36]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[lightfall.jar:git:lightfall-Bootstrap:1.20-R0.2-SNAPSHOT:63f9b1b:36]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[lightfall.jar:git:lightfall-Bootstrap:1.20-R0.2-SNAPSHOT:63f9b1b:36]
	at java.lang.Thread.run(Thread.java:840) [?:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 48
	at net.md_5.bungee.protocol.packet.Commands$ArgumentRegistry.read(Commands.java:904) ~[lightfall.jar:git:lightfall-Bootstrap:1.20-R0.2-SNAPSHOT:63f9b1b:36]
	at net.md_5.bungee.protocol.packet.Commands$ArgumentRegistry.access$000(Commands.java:307) ~[lightfall.jar:git:lightfall-Bootstrap:1.20-R0.2-SNAPSHOT:63f9b1b:36]
	at net.md_5.bungee.protocol.packet.Commands.read(Commands.java:84) ~[lightfall.jar:git:lightfall-Bootstrap:1.20-R0.2-SNAPSHOT:63f9b1b:36]
	at net.md_5.bungee.protocol.DefinedPacket.read(DefinedPacket.java:517) ~[lightfall.jar:git:lightfall-Bootstrap:1.20-R0.2-SNAPSHOT:63f9b1b:36]
	at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:62) ~[lightfall.jar:git:lightfall-Bootstrap:1.20-R0.2-SNAPSHOT:63f9b1b:36]
	at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:13) ~[lightfall.jar:git:lightfall-Bootstrap:1.20-R0.2-SNAPSHOT:63f9b1b:36]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88) ~[lightfall.jar:git:lightfall-Bootstrap:1.20-R0.2-SNAPSHOT:63f9b1b:36]
	... 27 more
[20:50:25 ERROR]: io.netty.handler.codec.DecoderException: java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 48
[20:50:25 ERROR]: 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:98)
[20:50:25 ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[20:50:25 ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[20:50:25 ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[20:50:25 ERROR]: 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[20:50:25 ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[20:50:25 ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[20:50:25 ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[20:50:25 ERROR]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
[20:50:25 ERROR]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:333)
[20:50:25 ERROR]: 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:454)
[20:50:25 ERROR]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
[20:50:25 ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[20:50:25 ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[20:50:25 ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[20:50:25 ERROR]: 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[20:50:25 ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
[20:50:25 ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[20:50:25 ERROR]: 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[20:50:25 ERROR]: 	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
[20:50:25 ERROR]: 	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe$1.run(AbstractEpollChannel.java:425)
[20:50:25 ERROR]: 	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
[20:50:25 ERROR]: 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
[20:50:25 ERROR]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[20:50:25 ERROR]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:413)
[20:50:25 ERROR]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[20:50:25 ERROR]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[20:50:25 ERROR]: 	at java.base/java.lang.Thread.run(Thread.java:840)
[20:50:25 ERROR]: Caused by: java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 48
[20:50:25 ERROR]: 	at net.md_5.bungee.protocol.packet.Commands$ArgumentRegistry.read(Commands.java:904)
[20:50:25 ERROR]: 	at net.md_5.bungee.protocol.packet.Commands$ArgumentRegistry.access$000(Commands.java:307)
[20:50:25 ERROR]: 	at net.md_5.bungee.protocol.packet.Commands.read(Commands.java:84)
[20:50:25 ERROR]: 	at net.md_5.bungee.protocol.DefinedPacket.read(DefinedPacket.java:517)
[20:50:25 ERROR]: 	at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:62)
[20:50:25 ERROR]: 	at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:13)
[20:50:25 ERROR]: 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)
[20:50:25 ERROR]: 	... 27 more
[20:50:25 INFO]: [Ghost_chu] disconnected with: The server you were previously on went down, you have been connected to a fallback server
```
