### ISSUE TITLE
使用模组 oculus 无法连接至 lightfall

### ISSUE THREAD

**Issue by Xing-C** [ArclightPowered/lightfall#43]
在客户端同时安装 
lightfallclient-1.1.0.jar
rubidium-0.6.2.jar
一切正常，但是安装
oculus-mc1.19.2-1.2.8a.jar
之后，单机正常，但当尝试加入lightfall服务端会失败
![image](https://user-images.githubusercontent.com/39401415/215238586-83e20f9a-85ee-445c-a6d2-41f241581e3f.png)
![image](https://user-images.githubusercontent.com/39401415/215238597-4957268f-92e5-499c-826a-bded7f2df4ca.png)

**Comment by Xing-C** [comment]
Lobby:

[10:56:22 INFO]: UUID of player Xing_Chen is 3e56b66b-551f-30ff-bfda-1f50cb073963
[10:56:22 INFO]: Xing_Chen[/192.168.10.101:56032] logged in with entity id 6117 at ([world]-485.49225383864825, 37.0625, 521.4999247398366)
[10:56:24 ERROR]: Couldn't register custom payload
java.lang.IllegalArgumentException: Channel must be entirely lowercase (attempted to use minecraft:BungeeCord)
        at org.bukkit.plugin.messaging.StandardMessenger.validateAndCorrectChannel(StandardMessenger.java:507) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.craftbukkit.v1_16_R3.entity.CraftPlayer.addChannel(CraftPlayer.java:1630) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:3054) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.PacketPlayInCustomPayload.a(SourceFile:44) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.PacketPlayInCustomPayload.a(SourceFile:9) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1271) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1264) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1225) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1139) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-794]
        at java.lang.Thread.run(Thread.java:831) [?:?]
[10:56:24 INFO]: Xing_Chen lost connection: Invalid payload REGISTER!

**Comment by Xing-C** [comment]
已知原因：Lobby服务端版本问题，更换到spigot 1.12.2正常

**Comment by Xing-C** [comment]
1
