### ISSUE TITLE
I cna't connect to my server 

### ISSUE THREAD

**Issue by Shykaruu** [ArclightPowered/lightfall#45]
I can't connect to my server with lightfall. Here the logs : [13:46:55 ERROR]: io.netty.handler.codec.DecoderException: java.lang.IllegalArgumentException: No provider for argument armourers_workshop:items
[13:46:55 ERROR]:       at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:98)
[13:46:55 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[13:46:55 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[13:46:55 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[13:46:55 ERROR]:       at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[13:46:55 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[13:46:55 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[13:46:55 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[13:46:55 ERROR]:       at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
[13:46:55 ERROR]:       at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
[13:46:55 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[13:46:55 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[13:46:55 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[13:46:55 ERROR]:       at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[13:46:55 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
[13:46:55 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[13:46:55 ERROR]:       at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[13:46:55 ERROR]:       at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
[13:46:55 ERROR]:       at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499)
[13:46:55 ERROR]:       at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397)
[13:46:55 ERROR]:       at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[13:46:55 ERROR]:       at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[13:46:55 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:833)
[13:46:55 ERROR]: Caused by: java.lang.IllegalArgumentException: No provider for argument armourers_workshop:items
[13:46:55 ERROR]:       at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145)
[13:46:55 ERROR]:       at net.md_5.bungee.protocol.packet.Commands$ArgumentRegistry.read(Commands.java:789)
[13:46:55 ERROR]:       at net.md_5.bungee.protocol.packet.Commands$ArgumentRegistry.access$000(Commands.java:307)
[13:46:55 ERROR]:       at net.md_5.bungee.protocol.packet.Commands.read(Commands.java:84)
[13:46:55 ERROR]:       at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:60)
[13:46:55 ERROR]:       at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:12)
[13:46:55 ERROR]:       at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)
[13:46:55 ERROR]:       ... 22 more

**Comment by Shykaruu** [comment]
it makes this error even if I remove the mods infact it does it as soon as I have a mod
