### ISSUE TITLE
i cant connect to my server

### ISSUE THREAD

**Issue by MVillabon** [ArclightPowered/lightfall#46]
could not decode packet! java.lang.IllegalArgumentException: No provider for argument crossstitch:mod_argument
[19:25:53 ERROR]: io.netty.handler.codec.DecoderException: java.lang.IllegalArgumentException: No provider for argument crossstitch:mod_argument
[19:25:53 ERROR]:       at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:98)
[19:25:53 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[19:25:53 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[19:25:53 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[19:25:53 ERROR]:       at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[19:25:53 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[19:25:53 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[19:25:53 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[19:25:53 ERROR]:       at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
[19:25:53 ERROR]:       at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
[19:25:53 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[19:25:53 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[19:25:53 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[19:25:53 ERROR]:       at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[19:25:53 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
[19:25:53 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[19:25:53 ERROR]:       at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[19:25:53 ERROR]:       at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
[19:25:53 ERROR]:       at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499)
[19:25:53 ERROR]:       at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397)
[19:25:53 ERROR]:       at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[19:25:53 ERROR]:       at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[19:25:53 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:833)
[19:25:53 ERROR]: Caused by: java.lang.IllegalArgumentException: No provider for argument crossstitch:mod_argument
[19:25:53 ERROR]:       at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145)
[19:25:53 ERROR]:       at net.md_5.bungee.protocol.packet.Commands$ArgumentRegistry.read(Commands.java:789)
[19:25:53 ERROR]:       at net.md_5.bungee.protocol.packet.Commands$ArgumentRegistry.access$000(Commands.java:307)
[19:25:53 ERROR]:       at net.md_5.bungee.protocol.packet.Commands.read(Commands.java:84)
[19:25:53 ERROR]:       at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:60)
[19:25:53 ERROR]:       at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:12)
[19:25:53 ERROR]:       at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)
[19:25:53 ERROR]:       ... 22 more

**Comment by MVillabon** [comment]
[19:25:46] [Netty Epoll Server IO #2/INFO] [co.li.co.ConfigSyncManager/]: Skipping config sync, No mods have registered a syncable config.
[19:25:47] [User Authenticator #1/INFO] [minecraft/ServerLoginNetHandler]: UUID of player CozimaChair is b7110b09-ac11-3cb4-968b-2b9641fab88e
[19:25:52] [Server thread/INFO] [ne.mi.co.AdvancementLoadFix/]: Using new advancement loading for net.minecraft.advancements.PlayerAdvancements@b216dd
[19:25:53] [Server thread/INFO] [minecraft/ServerPlayNetHandler]: CozimaChair lost connection: Disconnected
[19:25:53] [Server thread/INFO] [voicechat/]: Disconnecting client CozimaChair
[19:25:53] [Server thread/INFO] [minecraft/DedicatedServer]: CozimaChair left the game
[19:44:13] [Netty Epoll Server IO #2/INFO] [co.li.co.ConfigSyncManager/]: Skipping config sync, No mods have registered a syncable config.
[19:44:13] [User Authenticator #2/INFO] [minecraft/ServerLoginNetHandler]: UUID of player CozimaChair is b7110b09-ac11-3cb4-968b-2b9641fab88e
[19:44:18] [Server thread/INFO] [ne.mi.co.AdvancementLoadFix/]: Using new advancement loading for net.minecraft.advancements.PlayerAdvancements@11d3e274
[19:44:19] [Server thread/INFO] [minecraft/PlayerList]: CozimaChair[/179.1.129.135:54947] logged in with entity id 112 at ([world]77.5, 76.0, -247.5)
[19:44:19] [Server thread/INFO] [minecraft/ServerPlayNetHandler]: CozimaChair lost connection: Disconnected
[19:44:19] [Server thread/INFO] [voicechat/]: Disconnecting client CozimaChair
[19:44:19] [Server thread/INFO] [minecraft/DedicatedServer]: CozimaChair left the game
