### ISSUE TITLE
Timed out and the map doesn't load

### ISSUE THREAD

**Issue by pedrobalafina** [ArclightPowered/lightfall#63]
When I join the server the map doesn't load, just a void above me!
![image](https://github.com/ArclightPowered/lightfall/assets/134788279/824bd78f-ca92-42b3-8eca-6ac5d043bdb0)

The server is using this mods, forge 1.19.2:
![image](https://github.com/ArclightPowered/lightfall/assets/134788279/5783f464-60d8-45ea-adf1-474fcce46c64)

*Using DynMap plugin and the version of Arclight is 1.0.5...*

```
[17:04:33 ERROR] [STDERR]: java.net.ConnectException: Connection timed out: connect
[17:04:33 ERROR] [STDERR]:      at java.base/sun.nio.ch.Net.connect0(Native Method)
[17:04:33 ERROR] [STDERR]:      at java.base/sun.nio.ch.Net.connect(Net.java:589)
[17:04:33 ERROR] [STDERR]:      at java.base/sun.nio.ch.Net.connect(Net.java:578)
[17:04:33 ERROR] [STDERR]:      at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:583)
[17:04:33 ERROR] [STDERR]:      at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
[17:04:33 ERROR] [STDERR]:      at java.base/java.net.Socket.connect(Socket.java:751)
[17:04:33 ERROR] [STDERR]:      at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:304)
[17:04:33 ERROR] [STDERR]:      at java.base/sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:181)
[17:04:33 ERROR] [STDERR]:      at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:183)
[17:04:33 ERROR] [STDERR]:      at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:531)
[17:04:33 ERROR] [STDERR]:      at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:636)
[17:04:33 ERROR] [STDERR]:      at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
[17:04:33 ERROR] [STDERR]:      at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:377)
[17:04:33 ERROR] [STDERR]:      at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:193)
[17:04:33 ERROR] [STDERR]:      at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1237)
[17:04:33 ERROR] [STDERR]:      at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1123)
[17:04:33 ERROR] [STDERR]:      at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:179)
[17:04:33 ERROR] [STDERR]:      at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1675)
[17:04:33 ERROR] [STDERR]:      at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1599)
[17:04:33 ERROR] [STDERR]:      at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:223)
[17:04:33 ERROR] [STDERR]:      at java.base/java.net.URL.openStream(URL.java:1325)
[17:04:33 ERROR] [STDERR]:      at TRANSFORMER/minetraps@2.2.4/xxrexraptorxx.minetraps.world.Events.SupporterCheck(Events.java:130)
[17:04:33 ERROR] [STDERR]:      at TRANSFORMER/minetraps@2.2.4/xxrexraptorxx.minetraps.world.Events.SupporterRewards(Events.java:87)
[17:04:33 ERROR] [STDERR]:      at TRANSFORMER/minetraps@2.2.4/xxrexraptorxx.minetraps.world.__Events_SupporterRewards_PlayerLoggedInEvent.invoke(.dynamic)
[17:04:33 ERROR] [STDERR]:      at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
[17:04:33 ERROR] [STDERR]:      at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
[17:04:33 ERROR] [STDERR]:      at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
[17:04:33 ERROR] [STDERR]:      at TRANSFORMER/forge@43.3.8/net.minecraftforge.event.ForgeEventFactory.firePlayerLoggedIn(ForgeEventFactoryMixin.java:774)
[17:04:33 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.players.PlayerList.m_11261_(PlayerListMixin.java:246)
[17:04:33 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.network.ServerLoginPacketListenerImpl.m_10055_(ServerLoginNetHandlerMixin.java:624)
[17:04:33 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.network.ServerLoginPacketListenerImpl.m_9933_(ServerLoginNetHandlerMixin.java:75)
[17:04:33 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.19.2/net.minecraft.network.Connection.m_129483_(ConnectionMixin.java:248)
[17:04:33 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:143)
[17:04:33 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_5703_(MinecraftServerMixin.java:880)
[17:04:33 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServerMixin.java:292)
[17:04:33 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_5705_(MinecraftServerMixin.java:806)
[17:04:33 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServerMixin.java:2127)
[17:04:33 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServerMixin.java:244)
[17:04:33 ERROR] [STDERR]:      at java.base/java.lang.Thread.run(Thread.java:1583)
``` 

And the last line says: "[17:14:21 FATAL]: Preparing crash report with UUID 559db36e-e144-432b-8295-f288f1e7bd65"

**Comment by meepuru** [comment]
Please read the crash log carefully and you will find out it is not server side problem but caused  by the supporter check function of minetraps mod which hooked into login process, maybe the website it used to check is not reachable under your network.
Locate `path/to/your/world/serverconfig/minetraps-server.toml` and set `patreon_rewards` to false should solve your problem.
