### ISSUE TITLE
Can not login with some mods

### ISSUE THREAD

**Issue by DarthCY-K** [ArclightPowered/lightfall#7]
When i connected to the lightfall, it kicked me and say 'The server you were previously on went down, you have been connected to a fallback server'.

- Logs of lightfall
https://paste.ubuntu.com/p/z2McPC8JTv/

- Logs of arclight-forge-1.16-1.0.18-SNAPSHOT
https://paste.ubuntu.com/p/XYNc9fbDX5/

- Mods with this issue(Each has been single tested)
CraftTweaker-1.16.5-7.1.0.246
https://www.curseforge.com/minecraft/mc-mods/crafttweaker
https://github.com/CraftTweaker/CraftTweaker
ftb-quests-1605.2.1-build.39-forge
https://www.curseforge.com/minecraft/mc-mods/ftb-quests
https://github.com/FTBTeam/FTB-Quests
ftb-teams-1604.1.0.16-forge
https://www.curseforge.com/minecraft/mc-mods/ftb-teams
https://github.com/FTBTeam/FTB-Teams
Chunk+Pregenerator-V1.16-3.0.5
https://www.curseforge.com/minecraft/mc-mods/chunkpregenerator
enhancedcelestials-1.0.4-1.16.4
https://www.curseforge.com/minecraft/mc-mods/enhanced-celestials
https://github.com/CorgiTaco/Enhanced-Celestials
cleancut-mc1.16-2.2-forge
https://www.curseforge.com/minecraft/mc-mods/cleancut
https://github.com/Rongmario/CleanCut
fishingreal-1.16.3-1.0.0
https://www.curseforge.com/minecraft/mc-mods/fishing-real
ImmersiveEngineering-1.16.5-4.2.4-134
https://www.curseforge.com/minecraft/mc-mods/immersive-engineering
https://github.com/BluSunrize/ImmersiveEngineering
create-mc1.16.5_v0.3.1c
http://www.curseforge.com/minecraft/mc-mods/create
https://github.com/Creators-of-Create/Create
Bookshelf-1.16.5-10.0.7
https://www.curseforge.com/minecraft/mc-mods/bookshelf
https://github.com/Darkhax-Minecraft/Bookshelf
EvilCraft-1.16.5-1.1.2
https://minecraft.curseforge.com/projects/evilcraft
https://github.com/CyclopsMC/EvilCraft
curios-forge-1.16.5-4.0.5.1
https://www.curseforge.com/minecraft/mc-mods/curios
https://github.com/TheIllusiveC4/Curios
sophisticatedbackpacks-1.16.4-2.4.0.251
https://www.curseforge.com/minecraft/mc-mods/sophisticated-backpacks
https://github.com/P3pp3rF1y/SophisticatedBackpacks

**Comment by IzzelAliz** [comment]
This is very helpful information, thank you. Will investigate.

**Comment by Tomoli75** [comment]
Having similar issues too, downgrading the version of Create used seems to fix it, though Botania and Immersive Engineering don't seem to work at all.

**Comment by IzzelAliz** [comment]
Please test again with latest arclight and lightfall build

**Comment by Tomoli75** [comment]
Causing incompatabilities with ComputerCraft, `[18:01:57 ERROR]: io.netty.handler.codec.DecoderException: java.lang.IllegalArgumentException: No provider for argument computercraft:computer
[18:01:57 ERROR]:       at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:98)
[18:01:57 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[18:01:57 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[18:01:57 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[18:01:57 ERROR]:       at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
[18:01:57 ERROR]:       at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:311)
[18:01:57 ERROR]:       at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:432)
[18:01:57 ERROR]:       at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
[18:01:57 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[18:01:57 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[18:01:57 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[18:01:57 ERROR]:       at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[18:01:57 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[18:01:57 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[18:01:57 ERROR]:       at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[18:01:57 ERROR]:       at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795)
[18:01:57 ERROR]:       at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480)
[18:01:57 ERROR]:       at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
[18:01:57 ERROR]:       at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
[18:01:57 ERROR]:       at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[18:01:57 ERROR]:       at java.lang.Thread.run(Thread.java:748)
[18:01:57 ERROR]: Caused by: java.lang.IllegalArgumentException: No provider for argument computercraft:computer
[18:01:57 ERROR]:       at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
[18:01:57 ERROR]:       at net.md_5.bungee.protocol.packet.Commands$ArgumentRegistry.read(Commands.java:603)
[18:01:57 ERROR]:       at net.md_5.bungee.protocol.packet.Commands$ArgumentRegistry.access$000(Commands.java:308)
[18:01:57 ERROR]:       at net.md_5.bungee.protocol.packet.Commands.read(Commands.java:85)
[18:01:57 ERROR]:       at net.md_5.bungee.protocol.DefinedPacket.read(DefinedPacket.java:266)
[18:01:57 ERROR]:       at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:60)
[18:01:57 ERROR]:       at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:12)
[18:01:57 ERROR]:       at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)
[18:01:57 ERROR]:       ... 20 more`

**Comment by IzzelAliz** [comment]
You need to enable bungeecord mode in spigot.yml and use latest arclight build.2021年5月6日 00:03，Tomoli75 ***@***.***>写道：
Causing incompatabilities with ComputerCraft,
[18:01:57 ERROR]: io.netty.handler.codec.DecoderException: java.lang.IllegalArgumentException: No provider for argument computercraft:computer [18:01:57 ERROR]:       at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:98) [18:01:57 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [18:01:57 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [18:01:57 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [18:01:57 ERROR]:       at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) [18:01:57 ERROR]:       at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:311) [18:01:57 ERROR]:       at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:432) [18:01:57 ERROR]:       at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) [18:01:57 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [18:01:57 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [18:01:57 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [18:01:57 ERROR]:       at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [18:01:57 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [18:01:57 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [18:01:57 ERROR]:       at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [18:01:57 ERROR]:       at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795) [18:01:57 ERROR]:       at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480) [18:01:57 ERROR]:       at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) [18:01:57 ERROR]:       at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [18:01:57 ERROR]:       at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [18:01:57 ERROR]:       at java.lang.Thread.run(Thread.java:748) [18:01:57 ERROR]: Caused by: java.lang.IllegalArgumentException: No provider for argument computercraft:computer [18:01:57 ERROR]:       at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122) [18:01:57 ERROR]:       at net.md_5.bungee.protocol.packet.Commands$ArgumentRegistry.read(Commands.java:603) [18:01:57 ERROR]:       at net.md_5.bungee.protocol.packet.Commands$ArgumentRegistry.access$000(Commands.java:308) [18:01:57 ERROR]:       at net.md_5.bungee.protocol.packet.Commands.read(Commands.java:85) [18:01:57 ERROR]:       at net.md_5.bungee.protocol.DefinedPacket.read(DefinedPacket.java:266) [18:01:57 ERROR]:       at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:60) [18:01:57 ERROR]:       at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:12) [18:01:57 ERROR]:       at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88) [18:01:57 ERROR]:       ... 20 more

**Comment by Tomoli75** [comment]
Now using the correct build, and the client's console is disconnecting, then outputting
`[17:19:29] [Netty Client IO #2/ERROR] [minecraft/ArgumentTypes]: Could not deserialize arclight:wrapped`

https://images.tomoli.me/zevO1/LIwewaYA14.png is shown on the client's screen

Server log:
`[18:19:08 INFO]: [ThomasS|/:61730] <-> ServerConnector [ModsTest] has connected
[18:19:08 INFO]: ModsTest > [18:19:08] [User Authenticator #2/INFO] [minecraft/ServerLoginNetHandler]: UUID of player ThomasS is 36074dfc-0a44-31d3-9af6-a3eb6a7556b6
[18:19:08 INFO]: [/:61730|ThomasS] <-> DownstreamBridge <-> [hub] has disconnected
[18:19:29 INFO]: ModsTest > [18:19:29] [Server thread/INFO] [forge/AdvancementLoadFix]: Using new advancement loading for net.minecraft.advancements.PlayerAdvancements@4e3a8690
[18:19:29 INFO]: ModsTest > [18:19:29] [Server thread/INFO] [minecraft/PlayerList]: ThomasS[/:59563] logged in with entity id 86 at (-131.5, 69.0, 124.5)
[18:19:30 INFO]: [/:61730|ThomasS] -> UpstreamBridge has disconnected
[18:19:30 INFO]: [/:61730|ThomasS] <-> DownstreamBridge <-> [ModsTest] has disconnected
[18:19:30 INFO]: ModsTest > [18:19:30] [Server thread/INFO] [minecraft/ServerPlayNetHandler]: ThomasS lost connection: Disconnected
[18:19:30 INFO]: ModsTest > [18:19:30] [Server thread/INFO] [minecraft/DedicatedServer]: ThomasS left the game
[18:19:30 INFO]: ModsTest > [18:19:30] [Server thread/INFO] [minecraft/DedicatedServer]: Nothing changed. The player is not an operator`
BungeeCord mode is enabled in spigot.yml as well

**Comment by DarthCY-K** [comment]
Now most of these mods works well with lightfall, thank you.
But there are also some mods have the same issue, with more detailed lightfall logs.

- Here are lightfall logs:
create-mc1.16.5_v0.3.1c
https://paste.ubuntu.com/p/Bjg9VTw8zh/
ftb-teams-1604.1.0.16-forge
https://paste.ubuntu.com/p/yZtkXNHg2r/
Bookshelf-1.16.5-10.0.7
https://paste.ubuntu.com/p/mnKnY8Y6yx/

**Comment by IzzelAliz** [comment]
Please test again with latest arclight and lightfall build

**Comment by DarthCY-K** [comment]
> Please test again with latest arclight and lightfall build
This issue has been solved by using the latest build, thanks.
